#
version: '3.9'

services:
  db:
    container_name: ${DB_HOST}
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}

  bot:
    container_name: dvb
    depends_on: 
      - db
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - BOT_TOKEN

networks:
  default:
    name: dvb-net
